#pragma once
#include "prototype.h"

extern QC_BASIS_SET* QC_BASIS_STO_3G_PTR;
extern QC_BASIS_SET* QC_BASIS_3_21G_PTR;
extern QC_BASIS_SET* QC_BASIS_631G_PTR;
extern QC_BASIS_SET* QC_BASIS_631G_STAR_PTR;
extern QC_BASIS_SET* QC_BASIS_631G_STARSTAR_PTR;
extern QC_BASIS_SET* QC_BASIS_6311G_PTR;
extern QC_BASIS_SET* QC_BASIS_6311G_STAR_PTR;
extern QC_BASIS_SET* QC_BASIS_6311G_STARSTAR_PTR;
