mode = "nve"
dt = 0.00025
step_limit = 20000
write_information_interval = 10

cutoff = 8.0
skin = 2.0
coordinate_in_file = "heat_coordinate.txt"
velocity_in_file = "heat_velocity.txt"
mass_in_file = "mass.txt"
frc = "frc.dat"
print_zeroth_frame = 1

rst = "nve_long"

[REAXFF]
in_file = "ffield.reax.cho"
type_in_file = "type.txt"
